server:
  port: 0
spring:
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce-warehouse
    username: sa
    password: password
  sql:
    init:
      mode: always