server:
  port: 0

spring:
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce-shopping-store
    username: sa
    password: password
  sql:
    init:
      mode: always