aggregator:
  kafka:
    bootstrap-server: "localhost:9092"
    producer:
      properties:
        bootstrap.servers: ${aggregator.kafka.bootstrap-server}
        key.serializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value.serializer: "ru.yandex.practicum.kafka.deserializer.GeneralAvroSerializer"
      topic: "telemetry.snapshots.v1"
    consumer:
      properties:
        bootstrap.servers: ${aggregator.kafka.bootstrap-server}
        key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
        value.deserializer: "ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer"
        group.id: "telemetry.aggregator.sensors"
      topics:
        - "telemetry.sensors.v1"
      poll-timeout: 100ms