analyzer:
  kafka:
    snapshot-consumer:
      properties:
        bootstrap.servers: "localhost:9092"
        key.deserializer: "org.apache.kafka.common.serialization.StringSerializer"
        value.deserializer: "ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer"
        client.id: "telemetry.analyzer"
      topics:
        - "telemetry.snapshots.v1"
    hub-event-consumer:
      properties:
        bootstrap.servers: "localhost:9092"
        key.deserializer: "org.apache.kafka.common.serialization.StringSerializer"
        value.deserializer: "ru.yandex.practicum.kafka.deserializer.HubEventDeserializer"
        client.id: "telemetry.analyzer"
      topics:
        - "telemetry.hubs.v1"

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext